### ISSUE TITLE
Code Smell Issue

### ISSUE THREAD

**Issue by phishontop** [OxynDev/ExcerSec#4]
First of https://github.com/OxynDev/guardshield/blob/main/guardshield/main.py#L77C9-L81C1 could be simplied same issue with the next function after that
return self.dll.isDebugged() != 0 

next issue https://github.com/OxynDev/guardshield/blob/main/guardshield/main.py#L21 you could atleast use the is keyword instead of == check pep8 docs and look into what the eq dunder does

the are many more issues this are just the ones I want to point out. Please don't call me stupid or ban me for calling you out on selling source code which is free for $80.

**Comment by OxynDev** [comment]
Thanks for the advice number 1 and 2

And no i will ban u cuz u didn't saw my source and its not free so u will not say bullshit on my server
![988ad8e348b447060398378fa2bff68be01e90d5183cec4952d1c58e55d33ce3_3](https://github.com/OxynDev/guardshield/assets/98268537/013abcdf-ec6b-4d87-90ae-632d7af3c842)
