### ISSUE TITLE
You should add warning anti-injection may cause bugs in your application

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [OxynDev/ExcerSec#8]
Because anti-injection avoids some applications to run correctly. Actually it's not a bug it's just avoids application to inject python311.dll

**Comment by OxynDev** [comment]
> python311.dll

Can you explain better?

**Comment by OxynDev** [comment]
> Because anti-injection avoids some applications to run correctly. Actually it's not a bug it's just avoids application to inject python311.dll

Can you explain better?

**Comment by HydraDragonAntivirus** [comment]
> > Because anti-injection avoids some applications to run correctly. Actually it's not a bug it's just avoids application to inject python311.dll
> 
> Can you explain better?

Example if you want notify from notifypy import Notify then you try Notify it doesn't allow to inject python311.dll so it blocks notify the application.

**Comment by HydraDragonAntivirus** [comment]
Ok my enviroment is buggy also it's not important thing. Please look the issue  #9
